(function(c){function u(a){var e=a.data;a.isDefaultPrevented()||(a.preventDefault(),c(this).ajaxSubmit(e))}function t(a){var e=a.target,f=c(e);if(!f.is(":submit,input:image")){e=f.closest(":submit");if(0===e.length)return;e=e[0]}var b=this;b.clk=e;"image"==e.type&&(void 0!==a.offsetX?(b.clk_x=a.offsetX,b.clk_y=a.offsetY):"function"==typeof c.fn.offset?(f=f.offset(),b.clk_x=a.pageX-f.left,b.clk_y=a.pageY-f.top):(b.clk_x=a.pageX-e.offsetLeft,b.clk_y=a.pageY-e.offsetTop));setTimeout(function(){b.clk=
b.clk_x=b.clk_y=null},100)}function p(){if(c.fn.ajaxSubmit.debug){var a="[jquery.form] "+Array.prototype.join.call(arguments,"");window.console&&window.console.log?window.console.log(a):window.opera&&window.opera.postError&&window.opera.postError(a)}}var x,y;x=void 0!==c("<input type='file'/>").get(0).files;y=void 0!==window.FormData;c.fn.ajaxSubmit=function(a){function e(b){function e(){function a(){try{var b=(q.contentWindow?q.contentWindow.document:q.contentDocument?q.contentDocument:q.document).readyState;
p("state = "+b);b&&"uninitialized"==b.toLowerCase()&&setTimeout(a,50)}catch(c){p("Server abort: ",c," (",c.name,")"),j(x),t&&clearTimeout(t),t=void 0}}var b=i.attr("target"),h=i.attr("action");g.setAttribute("target",m);f||g.setAttribute("method","POST");h!=d.url&&g.setAttribute("action",d.url);!d.skipEncodingOverride&&(!f||/post/i.test(f))&&i.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});d.timeout&&(t=setTimeout(function(){u=!0;j(A)},d.timeout));var l=[];try{if(d.extraData)for(var k in d.extraData)d.extraData.hasOwnProperty(k)&&
l.push(c('<input type="hidden" name="'+k+'">').attr("value",d.extraData[k]).appendTo(g)[0]);d.iframeTarget||(v.appendTo("body"),q.attachEvent?q.attachEvent("onload",j):q.addEventListener("load",j,!1));setTimeout(a,15);g.submit()}finally{g.setAttribute("action",h),b?g.setAttribute("target",b):i.removeAttr("target"),c(l).remove()}}function j(a){if(!h.aborted&&!D){try{r=q.contentWindow?q.contentWindow.document:q.contentDocument?q.contentDocument:q.document}catch(b){p("cannot access response document: ",
b),a=x}if(a===A&&h)h.abort("timeout");else if(a==x&&h)h.abort("server abort");else if(r&&r.location.href!=d.iframeSrc||u){q.detachEvent?q.detachEvent("onload",j):q.removeEventListener("load",j,!1);var a="success",e;try{if(u)throw"timeout";var f="xml"==d.dataType||r.XMLDocument||c.isXMLDoc(r);p("isXml="+f);if(!f&&(window.opera&&(null===r.body||!r.body.innerHTML))&&--E){p("requeing onLoad callback, DOM not available");setTimeout(j,250);return}var g=r.body?r.body:r.documentElement;h.responseText=g?g.innerHTML:
null;h.responseXML=r.XMLDocument?r.XMLDocument:r;f&&(d.dataType="xml");h.getResponseHeader=function(a){return{"content-type":d.dataType}[a]};g&&(h.status=Number(g.getAttribute("status"))||h.status,h.statusText=g.getAttribute("statusText")||h.statusText);var i=(d.dataType||"").toLowerCase(),k=/(json|script|text)/.test(i);if(k||d.textarea){var m=r.getElementsByTagName("textarea")[0];if(m)h.responseText=m.value,h.status=Number(m.getAttribute("status"))||h.status,h.statusText=m.getAttribute("statusText")||
h.statusText;else if(k){var n=r.getElementsByTagName("pre")[0],z=r.getElementsByTagName("body")[0];n?h.responseText=n.textContent?n.textContent:n.innerText:z&&(h.responseText=z.textContent?z.textContent:z.innerText)}}else"xml"==i&&(!h.responseXML&&h.responseText)&&(h.responseXML=F(h.responseText));try{var f=h,g=d,s=f.getResponseHeader("content-type")||"",B="xml"===i||!i&&0<=s.indexOf("xml"),w=B?f.responseXML:f.responseText;B&&"parsererror"===w.documentElement.nodeName&&c.error&&c.error("parsererror");
g&&g.dataFilter&&(w=g.dataFilter(w,i));"string"===typeof w&&("json"===i||!i&&0<=s.indexOf("json")?w=G(w):("script"===i||!i&&0<=s.indexOf("javascript"))&&c.globalEval(w));y=w}catch(H){a="parsererror",h.error=e=H||a}}catch(C){p("error caught: ",C),a="error",h.error=e=C||a}h.aborted&&(p("upload aborted"),a=null);h.status&&(a=200<=h.status&&300>h.status||304===h.status?"success":"error");"success"===a?(d.success&&d.success.call(d.context,y,"success",h),l&&c.event.trigger("ajaxSuccess",[h,d])):a&&(void 0===
e&&(e=h.statusText),d.error&&d.error.call(d.context,h,a,e),l&&c.event.trigger("ajaxError",[h,d,e]));l&&c.event.trigger("ajaxComplete",[h,d]);l&&!--c.active&&c.event.trigger("ajaxStop");d.complete&&d.complete.call(d.context,h,a);D=!0;d.timeout&&clearTimeout(t);setTimeout(function(){d.iframeTarget||v.remove();h.responseXML=null},100)}}}var g=i[0],k,d,l,m,v,q,h,s,u,t;s=!!c.fn.prop;if(c(":input[name=submit],:input[id=submit]",g).length)alert('Error: Form elements must not have name or id of "submit".');
else{if(b)for(k=0;k<n.length;k++)b=c(n[k]),s?b.prop("disabled",!1):b.removeAttr("disabled");d=c.extend(!0,{},c.ajaxSettings,a);d.context=d.context||d;m="jqFormIO"+(new Date).getTime();d.iframeTarget?(v=c(d.iframeTarget),(b=v.attr("name"))?m=b:v.attr("name",m)):(v=c('<iframe name="'+m+'" src="'+d.iframeSrc+'" />'),v.css({position:"absolute",top:"-1000px",left:"-1000px"}));q=v[0];h={aborted:0,responseText:null,responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},
setRequestHeader:function(){},abort:function(a){var b="timeout"===a?"timeout":"aborted";p("aborting upload... "+b);this.aborted=1;v.attr("src",d.iframeSrc);h.error=b;d.error&&d.error.call(d.context,h,b,a);l&&c.event.trigger("ajaxError",[h,d,b]);d.complete&&d.complete.call(d.context,h,b)}};(l=d.global)&&0===c.active++&&c.event.trigger("ajaxStart");l&&c.event.trigger("ajaxSend",[h,d]);if(d.beforeSend&&!1===d.beforeSend.call(d.context,h,d))d.global&&c.active--;else if(!h.aborted){if(s=g.clk)if((b=s.name)&&
!s.disabled)d.extraData=d.extraData||{},d.extraData[b]=s.value,"image"==s.type&&(d.extraData[b+".x"]=g.clk_x,d.extraData[b+".y"]=g.clk_y);var A=1,x=2;s=c("meta[name=csrf-token]").attr("content");if((b=c("meta[name=csrf-param]").attr("content"))&&s)d.extraData=d.extraData||{},d.extraData[b]=s;d.forceSync?e():setTimeout(e,10);var y,r,E=50,D,F=c.parseXML||function(a,b){window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml");
return b&&b.documentElement&&"parsererror"!=b.documentElement.nodeName?b:null},G=c.parseJSON||function(a){return window.eval("("+a+")")}}}}if(!this.length)return p("ajaxSubmit: skipping submit process - no element selected"),this;var f,b,i=this;"function"==typeof a&&(a={success:a});f=this.attr("method");b=this.attr("action");(b=(b="string"===typeof b?c.trim(b):"")||window.location.href||"")&&(b=(b.match(/^([^#]+)/)||[])[1]);a=c.extend(!0,{url:b,success:c.ajaxSettings.success,type:f||"GET",iframeSrc:/^https/i.test(window.location.href||
"")?"javascript:false":"about:blank"},a);b={};this.trigger("form-pre-serialize",[this,a,b]);if(b.veto)return p("ajaxSubmit: submit vetoed via form-pre-serialize trigger"),this;if(a.beforeSerialize&&!1===a.beforeSerialize(this,a))return p("ajaxSubmit: submit aborted via beforeSerialize callback"),this;var g=a.traditional;void 0===g&&(g=c.ajaxSettings.traditional);var n=[],j,l=this.formToArray(a.semantic,n);a.data&&(a.extraData=a.data,j=c.param(a.data,g));if(a.beforeSubmit&&!1===a.beforeSubmit(l,this,
a))return p("ajaxSubmit: submit aborted via beforeSubmit callback"),this;this.trigger("form-submit-validate",[l,this,a,b]);if(b.veto)return p("ajaxSubmit: submit vetoed via form-submit-validate trigger"),this;b=c.param(l,g);j&&(b=b?b+"&"+j:j);"GET"==a.type.toUpperCase()?(a.url+=(0<=a.url.indexOf("?")?"&":"?")+b,a.data=null):a.data=b;var k=[];a.resetForm&&k.push(function(){i.resetForm()});a.clearForm&&k.push(function(){i.clearForm(a.includeHidden)});if(!a.dataType&&a.target){var A=a.success||function(){};
k.push(function(b){var e=a.replaceTarget?"replaceWith":"html";c(a.target)[e](b).each(A,arguments)})}else a.success&&k.push(a.success);a.success=function(b,c,e){for(var f=a.context||a,g=0,d=k.length;g<d;g++)k[g].apply(f,[b,c,e||i,i])};j=0<c("input:file:enabled[value]",this).length;b="multipart/form-data"==i.attr("enctype")||"multipart/form-data"==i.attr("encoding");g=x&&y;p("fileAPI :"+g);if(!1!==a.iframe&&(a.iframe||(j||b)&&!g))a.closeKeepAlive?c.get(a.closeKeepAlive,function(){e(l)}):e(l);else if((j||
b)&&g){var u=new FormData;for(j=0;j<l.length;j++)u.append(l[j].name,l[j].value);if(a.extraData)for(var m in a.extraData)a.extraData.hasOwnProperty(m)&&u.append(m,a.extraData[m]);a.data=null;m=c.extend(!0,{},c.ajaxSettings,a,{contentType:!1,processData:!1,cache:!1,type:"POST"});a.uploadProgress&&(m.xhr=function(){var b=jQuery.ajaxSettings.xhr();b.upload&&(b.upload.onprogress=function(b){var c=0,e=b.loaded||b.position,f=b.total;b.lengthComputable&&(c=Math.ceil(100*(e/f)));a.uploadProgress(b,e,f,c)});
return b});m.data=null;var t=m.beforeSend;m.beforeSend=function(b,c){c.data=u;t&&t.call(c,b,a)};c.ajax(m)}else c.ajax(a);for(m=0;m<n.length;m++)n[m]=null;this.trigger("form-submit-notify",[this,a]);return this};c.fn.ajaxForm=function(a){a=a||{};a.delegation=a.delegation&&c.isFunction(c.fn.on);if(!a.delegation&&0===this.length){var e=this.selector,f=this.context;if(!c.isReady&&e)return p("DOM not ready, queuing ajaxForm"),c(function(){c(e,f).ajaxForm(a)}),this;p("terminating; zero elements found by selector"+
(c.isReady?"":" (DOM not ready)"));return this}return a.delegation?(c(document).off("submit.form-plugin",this.selector,u).off("click.form-plugin",this.selector,t).on("submit.form-plugin",this.selector,a,u).on("click.form-plugin",this.selector,a,t),this):this.ajaxFormUnbind().bind("submit.form-plugin",a,u).bind("click.form-plugin",a,t)};c.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};c.fn.formToArray=function(a,e){var f=[];if(0===this.length)return f;var b=
this[0],i=a?b.getElementsByTagName("*"):b.elements;if(!i)return f;var g,n,j,l,k,p;g=0;for(p=i.length;g<p;g++)if(k=i[g],j=k.name)if(a&&b.clk&&"image"==k.type)!k.disabled&&b.clk==k&&(f.push({name:j,value:c(k).val(),type:k.type}),f.push({name:j+".x",value:b.clk_x},{name:j+".y",value:b.clk_y}));else if((l=c.fieldValue(k,!0))&&l.constructor==Array){e&&e.push(k);n=0;for(k=l.length;n<k;n++)f.push({name:j,value:l[n]})}else if(x&&"file"==k.type&&!k.disabled)if(e&&e.push(k),l=k.files,l.length)for(n=0;n<l.length;n++)f.push({name:j,
value:l[n],type:k.type});else f.push({name:j,value:"",type:k.type});else null!==l&&"undefined"!=typeof l&&(e&&e.push(k),f.push({name:j,value:l,type:k.type,required:k.required}));if(!a&&b.clk&&(i=c(b.clk),g=i[0],(j=g.name)&&!g.disabled&&"image"==g.type))f.push({name:j,value:i.val()}),f.push({name:j+".x",value:b.clk_x},{name:j+".y",value:b.clk_y});return f};c.fn.formSerialize=function(a){return c.param(this.formToArray(a))};c.fn.fieldSerialize=function(a){var e=[];this.each(function(){var f=this.name;
if(f){var b=c.fieldValue(this,a);if(b&&b.constructor==Array)for(var i=0,g=b.length;i<g;i++)e.push({name:f,value:b[i]});else null!==b&&"undefined"!=typeof b&&e.push({name:this.name,value:b})}});return c.param(e)};c.fn.fieldValue=function(a){for(var e=[],f=0,b=this.length;f<b;f++){var i=c.fieldValue(this[f],a);null===i||("undefined"==typeof i||i.constructor==Array&&!i.length)||(i.constructor==Array?c.merge(e,i):e.push(i))}return e};c.fieldValue=function(a,e){var f=a.name,b=a.type,i=a.tagName.toLowerCase();
void 0===e&&(e=!0);if(e&&(!f||a.disabled||"reset"==b||"button"==b||("checkbox"==b||"radio"==b)&&!a.checked||("submit"==b||"image"==b)&&a.form&&a.form.clk!=a||"select"==i&&-1==a.selectedIndex))return null;if("select"==i){var g=a.selectedIndex;if(0>g)return null;for(var f=[],i=a.options,n=(b="select-one"==b)?g+1:i.length,g=b?g:0;g<n;g++){var j=i[g];if(j.selected){var l=j.value;l||(l=j.attributes&&j.attributes.value&&!j.attributes.value.specified?j.text:j.value);if(b)return l;f.push(l)}}return f}return c(a).val()};
c.fn.clearForm=function(a){return this.each(function(){c("input,select,textarea",this).clearFields(a)})};c.fn.clearFields=c.fn.clearInputs=function(a){var e=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;return this.each(function(){var f=this.type,b=this.tagName.toLowerCase();if(e.test(f)||"textarea"==b)this.value="";else if("checkbox"==f||"radio"==f)this.checked=!1;else if("select"==b)this.selectedIndex=-1;else if(a&&(!0===a&&/hidden/.test(f)||"string"==
typeof a&&c(this).is(a)))this.value=""})};c.fn.resetForm=function(){return this.each(function(){("function"==typeof this.reset||"object"==typeof this.reset&&!this.reset.nodeType)&&this.reset()})};c.fn.enable=function(a){void 0===a&&(a=!0);return this.each(function(){this.disabled=!a})};c.fn.selected=function(a){void 0===a&&(a=!0);return this.each(function(){var e=this.type;"checkbox"==e||"radio"==e?this.checked=a:"option"==this.tagName.toLowerCase()&&(e=c(this).parent("select"),a&&(e[0]&&"select-one"==
e[0].type)&&e.find("option").selected(!1),this.selected=a)})};c.fn.ajaxSubmit.debug=!1})(jQuery);
